#!/usr/bin/env bash
# ============================================================================
#  scripts/setup_glm.sh — create the REPO-LOCAL GLM-OCR venv + config.
#
#  GLM-OCR is an OPTIONAL, third-party OCR engine vendored inside this repo at
#  <repo>/GLM-OCR. This script prepares it WITHOUT touching anything outside the
#  repo and without hardcoding any machine-specific path:
#
#    * creates the venv  <GLM_OCR_DIR>/.venv-mlx   (GLM_OCR_DIR defaults to
#      <repo>/GLM-OCR; override via GLM_OCR_DIR in .env)
#    * installs the glmocr SDK + selfhosted deps into it
#    * installs the MLX model server (mlx-vlm) — Apple Silicon only
#    * generates a selfhosted <GLM_OCR_DIR>/mlx_config.yaml if none exists
#
#  The MLX model server runs on Apple Silicon only. On other hosts the venv +
#  SDK still install (so paths resolve), but the model server cannot run — that
#  is fine: GLM stays optional and the rest of SmartDocs is unaffected.
# ============================================================================
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
. "$DIR/lib.sh"

load_env
normalize_env
ensure_dirs

info "GLM-OCR local setup"
hr
info "Repo root   : $REPO_ROOT"
info "GLM_OCR_DIR : $GLM_OCR_DIR"

# --- 1. Sanity: the vendored GLM-OCR code must be present -------------------
if [ ! -f "$GLM_OCR_DIR/pyproject.toml" ] && [ ! -d "$GLM_OCR_DIR/glmocr" ]; then
  err "No GLM-OCR project found at $GLM_OCR_DIR"
  err "Expected the vendored copy at <repo>/GLM-OCR, or set GLM_OCR_DIR in .env."
  exit 1
fi

# --- 2. Platform note (Apple Silicon required for the MLX server) -----------
IS_APPLE_SILICON=0
if [ "$(uname -s)" = "Darwin" ] && [ "$(uname -m)" = "arm64" ]; then
  IS_APPLE_SILICON=1
else
  warn "Host is not Apple Silicon — the MLX model server (mlx-vlm) cannot run here."
  warn "The venv + SDK will still install so paths resolve, but you can only run"
  warn "the GLM OCR engine end-to-end on an Apple-Silicon Mac."
fi

# --- 3. Create the venv -----------------------------------------------------
VENV="$GLM_OCR_DIR/.venv-mlx"
if [ -x "$VENV/bin/python" ]; then
  ok "GLM venv already exists: $VENV"
else
  command -v python3 >/dev/null 2>&1 || { err "python3 not found on PATH."; exit 1; }
  info "Creating GLM venv: $VENV"
  python3 -m venv "$VENV"
  ok "Created $VENV"
fi
GLM_PY="$VENV/bin/python"

# --- 4. Install the SDK + deps ---------------------------------------------
info "Upgrading pip…"
"$GLM_PY" -m pip install --upgrade pip >/dev/null

info "Installing glmocr SDK + selfhosted deps (torch/transformers — large)…"
"$GLM_PY" -m pip install "${GLM_OCR_DIR}[selfhosted]"
ok "glmocr SDK installed"

if [ "$IS_APPLE_SILICON" -eq 1 ]; then
  info "Installing MLX model server (mlx-vlm)…"
  if "$GLM_PY" -m pip install mlx-vlm; then
    ok "mlx-vlm installed"
  else
    warn "mlx-vlm install failed — you can retry: $GLM_PY -m pip install mlx-vlm"
  fi
else
  info "Skipping mlx-vlm (Apple Silicon only)."
fi

# --- 5. Generate a selfhosted config if none exists ------------------------
CFG="$GLM_OCR_DIR/mlx_config.yaml"
if [ -f "$CFG" ]; then
  ok "Config already present: $CFG (left untouched)"
else
  info "Writing selfhosted config: $CFG"
  cat > "$CFG" <<YAML
# Generated by scripts/setup_glm.sh — selfhosted MLX mode.
# Points the glmocr SDK at the local MLX model server (scripts/start_glm.sh).
pipeline:
  maas:
    enabled: false
  ocr_api:
    api_host: ${GLM_HOST}
    api_port: ${GLM_PORT}
    model: ${GLM_MODEL}
    api_mode: openai
    verify_ssl: false
YAML
  ok "Wrote $CFG"
fi

hr
ok "GLM setup complete."
echo
echo "Detected GLM python : $(glm_python 2>/dev/null || echo "$GLM_PY")"
echo
echo "Next:"
echo "  scripts/check.sh          # verify GLM paths / venv / health"
echo "  scripts/start_glm.sh -b   # start the GLM model server (Apple Silicon)"
echo "  scripts/start.sh          # full stack (starts GLM if ENABLE_GLM=true)"
